---
theme: basic
projects:

  - name: Helium
    id: 12345
    type: project
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Neon
    id: 12346
    type: project
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Boron
    id: 12347
    type: problem
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Steel
    id: 12348
    type: project
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Argon
    id: 12349
    type: project
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Oxygen
    id: 12347
    type: problem
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Uranium
    id: 12348
    type: project
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance

  - name: Cobalt
    id: 12349
    type: project
    work_categories:
      - process efficiency
      - controlled introduction
      - production change
      - RCA
      - compliance
